### ISSUE TITLE
GetRequestTelemetry() doesn't work with aysnc/await

### ISSUE THREAD

**Issue by ramondeklein** [Microsoft/ApplicationInsights-SDK-Labs#113]
When `OperationContext.Current.GetRequestTelemetry()` is used in an asynchronous WCF service, it won't be available after the first `await` operation. Most WCF services don't have a synchronization context -which is a good thing for scalability and performance- so the operation context won't be restored after an awaited call completes.

It seems that the underlying `WcfOperationContext` properly uses the `CallContext`, which flows properly with awaited code, but it is marked as `internal` and cannot be accessed from the outside. I did some digging around, but the request is available in the call-context after awaited calls.

When I add the following watch, then I can see the request (even after an awaited call):

```((Microsoft.ApplicationInsights.Wcf.Implementation.WcfOperationContext)((System.Runtime.Remoting.ObjectHandle)System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AIWcfOperationContext")).WrappedObject).Request```

I don't know about the implementation details of the underlying `WcfOperationContext` class, so I didn't write a pull-request.

**Comment by tomasr** [comment]
@ramondeklein Thanks for the feedback. It is true we're currently flowing the operation context internally so that our own code can fill in dependencies and other things correctly.

However, I believe the specific issue you're seeing is caused because when you're calling `OperationContext.Current`, it is returning null, so it triggers the following if inside `GetRequestTelemetry()`:

```C#
        public static RequestTelemetry GetRequestTelemetry(this OperationContext context)
        {
            // if causes it to return null if OperationContext.Current == null
            if (context == null)
            {
                return null;
            }

            var icontext = WcfOperationContext.FindContext(context);
            return icontext?.Request;
        }
```

I'll remove that if to enable your scenario, in which case we'll find the context in the `CallContext` and give you that.

**Comment by ramondeklein** [comment]
Although this will fix the issue, I think it's very awkward to call a method on a null variable. It would work, because it's an extension method but it doesn't feel right. Why obtain the telemetry from the operation context and not from the call-context instead?

**Comment by tomasr** [comment]
@ramondeklein It's a valid concern, though the only other option would just be to add a plain static method with no arguments. Not sure that is necessarily any better. The current method does have symmetry with the way the Web SDK works (which hangs the helper method of `HttpContext`).

Having it relate directly to the `CallContext` is not a good idea because right now this is an implementation detail that could change eventually (for example, .NET v4.6.x supports storing the operation context into an `AsyncLocal<T>` instance).
