### ISSUE TITLE
Catching handeled exceptions

### ISSUE THREAD

**Issue by jiberan** [Microsoft/ApplicationInsights-SDK-Labs#25]
Consider OperationContract, where Exception are catched and logged. By default, Application Insights SDK WCF Telemetry will mark this as succeeded request.

What would be best way to modify this behavior and mark this telemetry event as Exception? And also attach details about exception to this event?

Thanks.

```
// When called with 0, telemetry AppInsights event should be Exception.
public string GetData(int value)
{
     try
     {
          if (value ==0)
          {
               throw new ArgumentException();
          }
          return string.Format("You entered: {0}");
      }
      catch (Exception ex)
      {
            Logger.Log(ex);
            return string.Format("Request failed");
      }            
}
```

**Comment by tomasr** [comment]
@jiberan You can track an exception for a request simply by calling `TrackException()`:

```C#
public string GetData(int value)
{
     try
     {
          if (value ==0)
          {
               throw new ArgumentException();
          }
          return string.Format("You entered: {0}");
      }
      catch (Exception ex)
      {
            Logger.Log(ex);
            // this could be a global instance
            TelemetryClient client = new TelemetryClient();
            client.TrackException(ex);
            return string.Format("Request failed");
      }
}
```

As long as we can get at the WCF `OperationContext` associated with the request, the exception will be correctly tracked alongside it.

For your second question, there is, unfortunately, no way to manually marked the request as failed, because we're overriding the property value at the end of the request. I've just submitted a Pull Request that will fix this, and will allow you to do this:

```C#
var request = OperationContext.Current.GetRequestTelemetry();
request.Success = false;
```

**Comment by jiberan** [comment]
great. Thank you :-)

**Comment by SergeyKanzhelev** [comment]
New version with the fix should be available on MyGet. Thanks @tomasr

**Comment by jiberan** [comment]
@SergeyKanzhelev there is still old version (0.26.0-build00473) on MyGet. Can you check it? Thanks.

**Comment by abaranch** [comment]
By some reason new version is 0.25 and 0.26 was uploaded in June. I deleted version 0.26. You should be able to see a correct version now: 0.25.0-build34674, 15 Jul 2016 16:34:49 GMT or you can download it requesting the specific version.

**Comment by tomasr** [comment]
@abaranch It appears the version number was rolled back to 0.25 in this commit: https://github.com/Microsoft/ApplicationInsights-SDK-Labs/commit/330793d19eb0b2a4fad80c9f81a11ce50337661f
@SergeyKanzhelev Any reason for that change?

**Comment by SergeyKanzhelev** [comment]
Bad merge. Sorry. Anything else I lost with this commit?

**Comment by tomasr** [comment]
Possibly..... yes, since it ended up doing all these changes on the WCF folder:
![image](https://cloud.githubusercontent.com/assets/16179/16952707/efe9acbe-4d8f-11e6-9c31-6ff285cc0039.png)

I think it probably undid this merge https://github.com/Microsoft/ApplicationInsights-SDK-Labs/commit/d72fc66ffcb73107bef125714e6f62ff2ac4617e

**Comment by chatumbabub** [comment]
Any idea when fixed nuget package will be available? Thanks.
