### ISSUE TITLE
[AzureWeAppCounters] More custom counters support

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-SDK-Labs#59]
I inserted a list of custom counters Azure Web Apps seems to support:
https://github.com/Microsoft/ApplicationInsights-SDK-Labs/blob/customCounters/AggregateMetrics/AggregateMetrics/AzureWebApp/Implementation/CounterFactory.cs#L83

@mateoatr - please do association between those and json names.

**Comment by mateoatr** [comment]
At this time, there's no way to collect this counters, since we don't have the data:

`case @"\Process(??APP_WIN32_PROC??)\% Privileged Time": `
`case @"\Process(??APP_WIN32_PROC??)\Virtual Bytes Peak":`
`case @"\Process(??APP_WIN32_PROC??)\Virtual Bytes": `
`case @"\Process(??APP_WIN32_PROC??)\Working Set Peak": `
`case @"\Process(??APP_WIN32_PROC??)\Working Set": `
`case @"\Process(??APP_WIN32_PROC??)\Page File Bytes Peak": `
`case @"\Process(??APP_WIN32_PROC??)\Page File Bytes": `
`case @"\Process(??APP_WIN32_PROC??)\Priority Base": `
`case @"\Process(??APP_WIN32_PROC??)\Elapsed Time": `
`case @"\Process(??APP_WIN32_PROC??)\ID Process": `
`case @"\Process(??APP_WIN32_PROC??)\Creating Process ID": `
`case @"\Process(??APP_WIN32_PROC??)\Pool Paged Bytes": `
`case @"\Process(??APP_WIN32_PROC??)\Pool Nonpaged Bytes": `
`case @"\Process(??APP_WIN32_PROC??)\IO Data Operations / sec": `
`case @"\Process(??APP_WIN32_PROC??)\IO Data Bytes / sec": `
`case @"\.NET CLR Memory(??APP_CLR_PROC??)\Promoted Memory from Gen 0": `
`case @"\.NET CLR Memory(??APP_CLR_PROC??)\Promoted Memory from Gen 1": `
`case @"\.NET CLR Memory(??APP_CLR_PROC??)\Gen 0 Promoted Bytes/ Sec": `
`case @"\.NET CLR Memory(??APP_CLR_PROC??)\Gen 1 Promoted Bytes/ Sec": `
`case @"\.NET CLR Memory(??APP_CLR_PROC??)\Promoted Finalization-Memory from Gen 0": `
`case @"\.NET CLR Memory(??APP_CLR_PROC??)\Process ID": `
`case @"\.NET CLR Memory(??APP_CLR_PROC??)\# of Sink Blocks in use": `

However, for the following ones, we just need to implement a new type of gauge that is capable of calculating ratios:

`case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Cache Total Hit Ratio": `
`case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Cache API Hit Ratio": `
`case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Output Cache Hit Ratio": `
`case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Cache % Machine Memory Limit Used": `
`case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Cache % Process Memory Limit Used": `
`case @"\.NET CLR Memory(??APP_CLR_PROC??)\% Time in GC": `

**Comment by kartang** [comment]
I am planning to implement RatioGauge that computes the percentages (or ratio). Please let me know if the following correlation for the above mentioned performance counters is accurate:
a.	case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Cache Total Hit Ratio": **totalCacheHits/totalCacheMisses**
b.	case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Cache API Hit Ratio": **apiCacheHits/apiCacheMisses**
c.	case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Output Cache Hit Ratio": **outputCacheHits/ outputCacheMisses**
d.	case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Cache % Machine Memory Limit Used": **cachePercentMachMemLimitUsed/cachePercentMachMemLimitUsedBase**
e.	case @"\ASP.NET Applications(??APP_W3SVC_PROC??)\Cache % Process Memory Limit Used": **cachePercentProcMemLimitUsed/cachePercentProcMemLimitUsedBase * 100**
f.	case @"\.NET CLR Memory(??APP_CLR_PROC??)\% Time in GC": **timeInGC/timeInGCBase * 100**

**Comment by SergeyKanzhelev** [comment]
if you need ratio you need to divide by sum of misses and hits. Isn't it right?

I'm not sure what the `FooBase` is for. Most probably you are correct.
