### ISSUE TITLE
OnBeginRequest Change

### ISSUE THREAD

**Issue by SergeyBarskiy** [Microsoft/ApplicationInsights-SDK-Labs#77]
In order to log full message body with errors, IWcfTelemetryModule.OnBeginRequest should include Message request parameter.  Here is the proposed change:

void OnBeginRequest(IOperationContext operation, Message request);

**Comment by tomasr** [comment]
@SergeyBarskiy The original design was much like this, but I didn't want to expose that much directly. Notice, however, that this is not enough.

The signature would need to be:
```C#
void OnBeginRequest(IOperationContext operation, ref Message request);
```

Because chances are if you read the message, you'll need to replace it with a completely new buffered message, because otherwise processing the message will fail if the body stream has been consumed.

That said, I'm curious: Are you planning on logging the entire message body to AppInsights? Or somewhere else?

**Comment by tomasr** [comment]
OK, I've been looking at this and decided on a different approach.

Instead of changing the signature for all telemetry modules (which would also break anyone who's already depending on `IWcfTelemetryModule`), I'll introduce a separate interface (`IWcfMessageTrace`) for this:

```C#
    /// <summary>
    /// Represents a telemetry module that also is interested
    /// in tracing request messages before the request is executed.
    /// </summary>
    public interface IWcfMessageTrace
    {
        /// <summary>
        /// Called after IWcfTelemetryModule.OnBeginRequest()
        /// but before the request is executed.
        /// </summary>
        /// <param name="operation">The operation context</param>
        /// <param name="request">The request message. You can modify the request by returning a new, unread Message object.</param>
        void OnTraceRequest(IOperationContext operation, ref Message request);

        /// <summary>
        /// Called after the request is executed, but before
        /// IWcfTelemetryModule.OnEndRequest() is called.
        /// </summary>
        /// <param name="operation">The operation context</param>
        /// <param name="response">The response message. You can modify the response by returning a new, unread Message object.</param>
        void OnTraceResponse(IOperationContext operation, ref Message response);
    }
```

This way, supporting tracing messages would be seen as an __optional__ thing for modules, and would not add the overhead of additional calls.

This would add separate callbacks for tracing a request (right after `OnBeginRequest`) or a response message (right before `OnEndRequest`).

So if a telemetry module was interested in this, it would just need to implement an additional interface, and would automatically receive the additional callbacks.

Already have the code written and tested, but would like to ask for feedback on the approach.

Thoughts?

**Comment by SergeyBarskiy** [comment]
Sounds goo to me, Thomas.   Yes, I am planning to log the message to AppInsights, but I have not decide if I am going to do this for request or just errors.  Probably just errors.  If we read and replace message in Before, I would need access to it in the After, since I really want to log the responce, not really a reply.  I feel some people may want to log reply as well.   As a result, it would need to be persisted in OperaionContext somehow.  So, does it need a property of type Message for Request and Responce in order to provide access to them outside of OnTraceRequest?
Thanks you!

**Comment by SergeyBarskiy** [comment]
I hate to pile on, so tell me if I need to open another issue.  There is currently no way to inject custom properties into telemetry.  I had to create / override exception tracking module to do so.  Not a big deal, but so far we found that we always want to add custom properties. I could not come up with a clean way to do it without custom module vs exception module that is included.  Thanks again.  Great work!  Saved me many hours.

**Comment by tomasr** [comment]
@SergeyBarskiy I'm not sure I fully understand your scenario.... are you talking about logging the response message containing the SOAP fault? Or something else?

As for your second issue, you should be able to write an `ITelemetryInitializer`. If that's not fitting your needs for whatever reason, do open a separate issue so that we can track it separately :smile:.

**Comment by SergeyBarskiy** [comment]
I'll give it some more though and post back if needed.  Thanks again, Tomas!

**Comment by tomasr** [comment]
@SergeyBarskiy Have you identified more closely what your requirement is? I'd like to make sure we're supporting it correctly!

**Comment by tomasr** [comment]
Since the proposed solution was implemented, closing this.
